// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_hidden_achievement_3 = "CgkIrvvlo4wZEAIQGg"; // <GPGSID>
        public const string achievement_achievement_2 = "CgkIrvvlo4wZEAIQFA"; // <GPGSID>
        public const string achievement_achievement_3 = "CgkIrvvlo4wZEAIQFQ"; // <GPGSID>
        public const string achievement_achievement_1 = "CgkIrvvlo4wZEAIQEw"; // <GPGSID>
        public const string achievement_hidden_achievement_1 = "CgkIrvvlo4wZEAIQGA"; // <GPGSID>
        public const string achievement_achievement_4 = "CgkIrvvlo4wZEAIQFg"; // <GPGSID>
        public const string achievement_achievement_5 = "CgkIrvvlo4wZEAIQFw"; // <GPGSID>
        public const string leaderboard_leaderboard_1_student_2 = "CgkIrvvlo4wZEAIQIw"; // <GPGSID>
        public const string achievement_hidden_achievement_2 = "CgkIrvvlo4wZEAIQGQ"; // <GPGSID>
        public const string achievement_hidden_achievement_5 = "CgkIrvvlo4wZEAIQHA"; // <GPGSID>
        public const string leaderboard_leaderboard_2_student_2 = "CgkIrvvlo4wZEAIQKw"; // <GPGSID>
        public const string achievement_incremental_achievement_1 = "CgkIrvvlo4wZEAIQHQ"; // <GPGSID>
        public const string achievement_incremental_achievement_2 = "CgkIrvvlo4wZEAIQHg"; // <GPGSID>
        public const string achievement_incremental_achievement_3 = "CgkIrvvlo4wZEAIQHw"; // <GPGSID>
        public const string achievement_incremental_achievement_4 = "CgkIrvvlo4wZEAIQIA"; // <GPGSID>
        public const string achievement_incremental_achievement_5 = "CgkIrvvlo4wZEAIQIQ"; // <GPGSID>
        public const string achievement_hidden_achievement_4 = "CgkIrvvlo4wZEAIQGw"; // <GPGSID>

}

